security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\UserAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/group, roles: ROLE_ADMIN }
        - { path: ^/reports, roles: ROLE_ADMIN }
        - { path: ^/system-settings, roles: ROLE_ADMIN }
        - { path: ^/audit-logs, roles: ROLE_ADMIN }
        - { path: ^/student/group, roles: [ROLE_ADMIN, ROLE_TEACHER] }
        - { path: ^/course, roles: [ROLE_ADMIN, ROLE_TEACHER] }
        - { path: ^/teacher, roles: [ROLE_ADMIN, ROLE_TEACHER] }
        - { path: ^/student, roles: ROLE_STUDENT }
